"""Initianal migration

Revision ID: 03e45a3ea2c0
Revises: c687dc4716e6
Create Date: 2024-03-28 17:50:02.207308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03e45a3ea2c0'
down_revision = 'c687dc4716e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
