"""Initianal migration

Revision ID: 0600c4a8eb32
Revises: 9e47687ddfe4
Create Date: 2024-03-28 17:18:38.147741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0600c4a8eb32'
down_revision = '9e47687ddfe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
