"""1 migration

Revision ID: 070b03cd3a78
Revises: 265bb89c92c9
Create Date: 2024-04-20 17:01:24.828425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '070b03cd3a78'
down_revision = '265bb89c92c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
