"""Initianal migration

Revision ID: 0bb584457f68
Revises: deb760e8b6da
Create Date: 2024-03-28 15:45:09.455875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bb584457f68'
down_revision = 'deb760e8b6da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
