"""Initianal migration

Revision ID: 11cfe4d53523
Revises: 6ba15ae2887b
Create Date: 2024-03-28 17:04:57.207889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11cfe4d53523'
down_revision = '6ba15ae2887b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
