"""1 migration

Revision ID: 1acc556fff85
Revises: 
Create Date: 2024-04-15 18:59:03.729322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1acc556fff85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tguser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=True),
    sa.Column('tg_username', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('lastname', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_user_id'),
    sa.UniqueConstraint('tg_username')
    )
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('target_date', sa.String(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['tg_user_id'], ['tguser.tg_user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('company_inn', sa.BigInteger(), nullable=True),
    sa.Column('company_add_date', sa.DateTime(), nullable=True),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['tg_user_id'], ['tguser.tg_user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_inn')
    )
    op.create_table('applicationcompany',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_application', sa.BigInteger(), nullable=True),
    sa.Column('company_inn', sa.BigInteger(), nullable=True),
    sa.Column('payer_or_recipient_status', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['company_inn'], ['company.company_inn'], ),
    sa.ForeignKeyConstraint(['id_application'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applicationcompany')
    op.drop_table('company')
    op.drop_table('application')
    op.drop_table('user')
    op.drop_table('tguser')
    # ### end Alembic commands ###
