"""Initianal migration

Revision ID: 43280c442162
Revises: fb5e331e1124
Create Date: 2024-03-28 17:35:47.928280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43280c442162'
down_revision = 'fb5e331e1124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
