"""Initianal migration

Revision ID: 4c3aa71f0562
Revises: 9fda3357c235
Create Date: 2024-03-28 17:54:46.877585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c3aa71f0562'
down_revision = '9fda3357c235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
