"""Initianal migration

Revision ID: 4f712dd75507
Revises: b05a7786347f
Create Date: 2024-03-28 17:44:30.570230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f712dd75507'
down_revision = 'b05a7786347f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
