"""Initianal migration

Revision ID: 59d3071b2d6d
Revises: f7f1a709e225
Create Date: 2024-03-28 17:30:04.484313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59d3071b2d6d'
down_revision = 'f7f1a709e225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
