"""Initianal migration

Revision ID: 5f3a7315b4e7
Revises: b084cb58d15f
Create Date: 2024-03-28 16:36:50.549674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f3a7315b4e7'
down_revision = 'b084cb58d15f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
