"""Initianal migration

Revision ID: 6ba15ae2887b
Revises: f6bc3d1be7c9
Create Date: 2024-03-28 17:01:44.125806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ba15ae2887b'
down_revision = 'f6bc3d1be7c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
