"""Initianal migration

Revision ID: 9e47687ddfe4
Revises: d59e986458a6
Create Date: 2024-03-28 17:16:11.532615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e47687ddfe4'
down_revision = 'd59e986458a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
