"""Initianal migration

Revision ID: 9fda3357c235
Revises: 03e45a3ea2c0
Create Date: 2024-03-28 17:53:11.542937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fda3357c235'
down_revision = '03e45a3ea2c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
