"""Initianal migration

Revision ID: a6782c27cc29
Revises: 0bb584457f68
Create Date: 2024-03-28 16:15:59.711672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6782c27cc29'
down_revision = '0bb584457f68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
