"""Initianal migration

Revision ID: a7cd694dfa22
Revises: 5f3a7315b4e7
Create Date: 2024-03-28 16:40:42.737007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7cd694dfa22'
down_revision = '5f3a7315b4e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
