"""Initianal migration

Revision ID: b05a7786347f
Revises: daa07fd9a8df
Create Date: 2024-03-28 17:42:21.512433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b05a7786347f'
down_revision = 'daa07fd9a8df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
