"""Initianal migration

Revision ID: b084cb58d15f
Revises: a6782c27cc29
Create Date: 2024-03-28 16:29:33.961454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b084cb58d15f'
down_revision = 'a6782c27cc29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
