"""Initianal migration

Revision ID: c687dc4716e6
Revises: 4f712dd75507
Create Date: 2024-03-28 17:47:11.126517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c687dc4716e6'
down_revision = '4f712dd75507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
