"""Initianal migration

Revision ID: cb3d955b8ad6
Revises: 59d3071b2d6d
Create Date: 2024-03-28 17:32:21.635698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb3d955b8ad6'
down_revision = '59d3071b2d6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
