"""Initianal migration

Revision ID: cd4671c32b5e
Revises: 4c3aa71f0562
Create Date: 2024-03-28 18:02:01.131074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd4671c32b5e'
down_revision = '4c3aa71f0562'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
