"""Initianal migration

Revision ID: d59e986458a6
Revises: 11cfe4d53523
Create Date: 2024-03-28 17:12:29.556475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd59e986458a6'
down_revision = '11cfe4d53523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
