"""Initianal migration

Revision ID: daa07fd9a8df
Revises: df03d7e22c4b
Create Date: 2024-03-28 17:38:44.650864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daa07fd9a8df'
down_revision = 'df03d7e22c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
