"""Initianal migration

Revision ID: deb760e8b6da
Revises: 677c34ce52c0
Create Date: 2024-03-28 15:40:09.463369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deb760e8b6da'
down_revision = '677c34ce52c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
