"""Initianal migration

Revision ID: df03d7e22c4b
Revises: 43280c442162
Create Date: 2024-03-28 17:37:21.404497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df03d7e22c4b'
down_revision = '43280c442162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
