"""Initianal migration

Revision ID: f6bc3d1be7c9
Revises: a7cd694dfa22
Create Date: 2024-03-28 16:57:56.915496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6bc3d1be7c9'
down_revision = 'a7cd694dfa22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
