"""Initianal migration

Revision ID: f7f1a709e225
Revises: 0600c4a8eb32
Create Date: 2024-03-28 17:27:35.891146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7f1a709e225'
down_revision = '0600c4a8eb32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
