"""Initianal migration

Revision ID: fb5e331e1124
Revises: cb3d955b8ad6
Create Date: 2024-03-28 17:34:23.046393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb5e331e1124'
down_revision = 'cb3d955b8ad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
