"""Initianal migration

Revision ID: fc39996b2f03
Revises: cd4671c32b5e
Create Date: 2024-03-28 18:04:33.299917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc39996b2f03'
down_revision = 'cd4671c32b5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
